version: '3'

services:
  api:
    container_name: linux-ludo-api
    build:
      context: ../src/
      dockerfile: LinuxLudo.API/Dockerfile
    ports:
      - "80:80"
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database=ludo;username=root;password=secret"
    networks:
      - db
      - api
  db:
    image: postgres:13.2
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ludo
    ports:
      - "5432:5432"
    volumes:
      - test:/var/lib/postgresql/data
    networks:
      - db

volumes:
  test:
    driver: local

networks:
  db:
    driver: bridge
  api:
    driver: bridge
