version: '3'

networks:
  api:
  db:

services:
  web:
    container_name: web
    build:
      context: ../src/
      dockerfile: LinuxLudo.Web/Dockerfile
    environment:
      API_URL: "http://api"
    ports:
      - "80:80"
    networks:
      - api

  api:
    container_name: api
    build:
      context: ../src/
      dockerfile: LinuxLudo.API/Dockerfile
    environment:
      DB_CONNECTION_STRING: "host=db;port=5432;database=ludo;username=root;password=secret"
    networks:
      - db
      - api
  db:
    image: postgres:13.2
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ludo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db

volumes:
  pgdata:
    driver: local
