version: '3'

networks:
  api:
  db:

services:
  web:
    image: thenerdyhamster/ludo-web
    container_name: web
    environment:
      API_URL: "http://api"
    ports:
      - "80:80"
    networks:
      - api

  api:
    image: thenerdyhamster/ludo-api
    container_name: api
    environment:
      DB_CONNECTION_STRING: "host=db;port=${DB_PORT};database=${DB_NAME};username=${DB_USER};password=${DB_PWD}"
    networks:
      - db
      - api
  db:
    image: postgres:13.2
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - db

volumes:
  pgdata:
    driver: local
